services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://mlops:mlops@db:5432/mlops
    ports: ["8000:8000"]
    depends_on: [db]

  frontend:
    build: ./frontend
    ports: ["4200:80"]
    depends_on: [backend]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
      POSTGRES_DB: mlops
    ports: ["5432:5432"]
